services:
    db:
        image: postgres:16
        container_name: jugamir_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: jugamirdb
        ports:
            - "5432:5432" #en produccion se quita
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
            - ./db/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d jugamirdb"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 900s

    pgadmin:
        image: dpage/pgadmin4
        container_name: jugamir_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - "5050:80" #en produccion se quita
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - db
    
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        container_name: jugamir_backend
        restart: unless-stopped
        volumes:
            - ./backend/src/main/resources/static:/app/static #en produccion se quita
            #- imagenes_data:/app/static #en produccion se descomenta y se sustituye por lo de arriba
        environment:
            DB_HOST: db
            DB_PORT: 5432 #en produccion se quita
            DB_NAME: jugamirdb
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            SERVER_PORT: 8080
            SHOW_SQL: false
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            SCRIPTS_PATH: /app/db
            IMAGENES_PATH: /app/static
            APP_URL: ${APP_URL:-http://localhost:3000}
        ports:
            - "8080:8080"
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        container_name: jugamir_frontend
        restart: unless-stopped
        ports:
            - "3000:80" 
        depends_on:
            - backend

volumes:
    postgres_data:
    pgadmin_data:
    #imagenes_data: #en produccion se descomenta
        

    